/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.farmaciasystem.Presentacion.Modulos;

/**
 *
 * @author Frank
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProdBajS = new javax.swing.JButton();
        lblProductosMasVendidos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMasVendidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbStockBajo = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblProdBajS.setBackground(new java.awt.Color(255, 204, 204));
        lblProdBajS.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lblProdBajS.setForeground(new java.awt.Color(51, 51, 51));
        lblProdBajS.setText("Productos con bajo stock !!");
        lblProdBajS.setBorder(null);
        lblProdBajS.setIconTextGap(15);
        lblProdBajS.setMargin(new java.awt.Insets(10, 14, 10, 14));
        lblProdBajS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdBajSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProdBajSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProdBajSMouseExited(evt);
            }
        });
        lblProdBajS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProdBajSActionPerformed(evt);
            }
        });

        lblProductosMasVendidos.setBackground(new java.awt.Color(204, 255, 204));
        lblProductosMasVendidos.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lblProductosMasVendidos.setForeground(new java.awt.Color(51, 51, 51));
        lblProductosMasVendidos.setText("Productos más vendidos");
        lblProductosMasVendidos.setBorder(null);
        lblProductosMasVendidos.setIconTextGap(15);
        lblProductosMasVendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosMasVendidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductosMasVendidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductosMasVendidosMouseExited(evt);
            }
        });
        lblProductosMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProductosMasVendidosActionPerformed(evt);
            }
        });

        tbMasVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbMasVendidos);

        tbStockBajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbStockBajo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblProdBajS, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductosMasVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdBajS)
                    .addComponent(lblProductosMasVendidos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblProdBajSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdBajSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdBajSMouseClicked

    private void lblProdBajSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdBajSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdBajSMouseEntered

    private void lblProdBajSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdBajSMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdBajSMouseExited

    private void lblProdBajSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProdBajSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProdBajSActionPerformed

    private void lblProductosMasVendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMasVendidosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProductosMasVendidosMouseClicked

    private void lblProductosMasVendidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMasVendidosMouseEntered

    }//GEN-LAST:event_lblProductosMasVendidosMouseEntered

    private void lblProductosMasVendidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMasVendidosMouseExited

    }//GEN-LAST:event_lblProductosMasVendidosMouseExited

    private void lblProductosMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProductosMasVendidosActionPerformed

    }//GEN-LAST:event_lblProductosMasVendidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lblProdBajS;
    private javax.swing.JButton lblProductosMasVendidos;
    private javax.swing.JTable tbMasVendidos;
    private javax.swing.JTable tbStockBajo;
    // End of variables declaration//GEN-END:variables
}
