/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.farmaciasystem.Presentacion.Modulos;

import com.mycompany.farmaciasystem.Presentacion.FormsADD.NuevosProductos;
import com.mycompany.farmaciasystem.Presentacion.FormsEditar.EditarProducto;
import com.mycompany.farmaciasystem.controladores.ProductoController;
import com.mycompany.farmaciasystem.factory.IReporte;
import com.mycompany.farmaciasystem.factory.ReportesFactory;
import com.mycompany.farmaciasystem.modelo.entidades.Producto;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frank
 */
public class Productos extends javax.swing.JPanel {

    private ProductoController productoController = new ProductoController();
    private DefaultTableModel modeloTabla; 
    JFrame Principal = (JFrame) SwingUtilities.getWindowAncestor(this);

    /**
     * Creates new form NewJPanel
     */
    public Productos() {
        initComponents();
        OtrosComponentes();
        CargarTablaProductos();

    }

    private void OtrosComponentes() {
        txtBuscar.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del producto...");
    }

    public final void CargarTablaProductos() {

        modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };

        String titulos[] = {"ID", "Nombre", "Descripción", "Precio", "Stock Actual", "Stock Mínimo", "Estado"};
        modeloTabla.setColumnIdentifiers(titulos);

        tbProductos.setModel(modeloTabla);
        tbProductos.getTableHeader().setReorderingAllowed(false);
        tbProductos.getTableHeader().setFont(new Font("poppins semibold", Font.BOLD, 12));
        tbProductos.getTableHeader().setBackground(new Color(207, 250, 254));

        // Cargar datos iniciales desde la base de datos
        productoController.cargarProductosEnTabla(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarProductos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        btnRepInvent = new javax.swing.JButton();
        btnRepoBajoStock = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 37, 41));
        jLabel1.setText("Lista de Productos");

        btnAgregarProductos.setBackground(new java.awt.Color(32, 138, 215));
        btnAgregarProductos.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        btnAgregarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProductos.setText("Agregar Producto");
        btnAgregarProductos.setBorder(null);
        btnAgregarProductos.setFocusPainted(false);
        btnAgregarProductos.setFocusable(false);
        btnAgregarProductos.setIconTextGap(6);
        btnAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Buscar producto : ");

        txtBuscar.setBackground(new java.awt.Color(242, 242, 242));
        txtBuscar.setBorder(null);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Acciones : ");

        btnEditar.setBackground(new java.awt.Color(242, 242, 242));
        btnEditar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(51, 51, 51));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/edit_square_30dp_5084C1_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setFocusPainted(false);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(242, 242, 242));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/Elimar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbProductos);

        btnRepInvent.setBackground(new java.awt.Color(242, 242, 242));
        btnRepInvent.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnRepInvent.setForeground(new java.awt.Color(51, 51, 51));
        btnRepInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/edit_square_30dp_5084C1_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnRepInvent.setText("Generar reporte inventario");
        btnRepInvent.setBorder(null);
        btnRepInvent.setBorderPainted(false);
        btnRepInvent.setFocusPainted(false);
        btnRepInvent.setFocusable(false);
        btnRepInvent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRepInvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepInventActionPerformed(evt);
            }
        });

        btnRepoBajoStock.setBackground(new java.awt.Color(242, 242, 242));
        btnRepoBajoStock.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnRepoBajoStock.setForeground(new java.awt.Color(51, 51, 51));
        btnRepoBajoStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/edit_square_30dp_5084C1_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnRepoBajoStock.setText("Generar reporte bajo stock");
        btnRepoBajoStock.setBorder(null);
        btnRepoBajoStock.setBorderPainted(false);
        btnRepoBajoStock.setFocusPainted(false);
        btnRepoBajoStock.setFocusable(false);
        btnRepoBajoStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRepoBajoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepoBajoStockActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(242, 242, 242));
        btnBuscar.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(51, 51, 51));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/search_30dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setFocusPainted(false);
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscar.setIconTextGap(5);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRepInvent, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnRepoBajoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepInvent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRepoBajoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductosActionPerformed

        NuevosProductos ventanaProduc = new NuevosProductos(Principal);
        ventanaProduc.setVisible(true);
        CargarTablaProductos();

    }//GEN-LAST:event_btnAgregarProductosActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        int fila = tbProductos.getSelectedRow();
        if (fila >= 0) {
            int id = Integer.parseInt(tbProductos.getValueAt(fila, 0).toString());

            EditarProducto ventanaEditar = new EditarProducto(Principal);
            ventanaEditar.cargarDatos(id);
            ventanaEditar.setVisible(true);

            CargarTablaProductos(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto.");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int fila = tbProductos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el producto a eliminar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idProducto = Integer.parseInt(tbProductos.getValueAt(fila, 0).toString());
        String nombre = tbProductos.getValueAt(fila, 1).toString();

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el producto '" + nombre + "'?\nEsto lo desactivará del sistema.",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            boolean exito = productoController.eliminarProducto(idProducto);
            if (exito) {
                JOptionPane.showMessageDialog(this, "Producto eliminado correctamente.");
                CargarTablaProductos(); // Recargar tabla
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el producto.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRepInventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepInventActionPerformed
        try {
            List<Producto> lista = productoController.obtenerTodosLosProductos();

            IReporte reporte = ReportesFactory.crearReporte(ReportesFactory.TipoReporte.INVENTARIO, lista);

            generarYGuardarReporte(reporte);

        } catch (Exception e) {
            e.toString();
        }    }//GEN-LAST:event_btnRepInventActionPerformed

    private void btnRepoBajoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepoBajoStockActionPerformed
        try {
            List<Producto> lista = productoController.obtenerProductosBajoStock();

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay productos con bajo stock.");
                return;
            }

            IReporte reporte = ReportesFactory.crearReporte(ReportesFactory.TipoReporte.BAJO_STOCK, lista);

            generarYGuardarReporte(reporte);

        } catch (HeadlessException e) {
            e.printStackTrace();
        }    }//GEN-LAST:event_btnRepoBajoStockActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String criterio = txtBuscar.getText().trim();

        // Limpiarvisualmente la tabla
        DefaultTableModel modelo = (DefaultTableModel) tbProductos.getModel();
        modelo.setRowCount(0);

        java.util.List<Producto> lista;

        if (criterio.isEmpty()) {
            // Si está vacío, traemos todos los activos
            lista = productoController.obtenerTodosLosProductos();
        } else {
            lista = productoController.buscarProductosPorNombre(criterio);
        }

        // Rellenar la tabla
        for (Producto p : lista) {
            Object[] fila = {
                p.getIdProducto(),
                p.getNombre(),
                p.getIdCategoria(), // O p.getCategoriaNombre() si lo tienes
                p.getIdEmpresaFabricante(), // O el nombre del laboratorio
                p.getPrecioVenta(),
                p.getStockActual(),
                p.getStockMinimo(),
                p.getDescripcion()
            };
            modelo.addRow(fila);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void generarYGuardarReporte(IReporte reporte) {
        reporte.generarReporte();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new File(reporte.obtenerNombreArchivo()));

        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try (FileOutputStream fos = new FileOutputStream(fileChooser.getSelectedFile())) {
                fos.write(reporte.obtenerBytes());
                JOptionPane.showMessageDialog(this, "Reporte guardado exitosamente.");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error IO: " + ex.getMessage());
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRepInvent;
    private javax.swing.JButton btnRepoBajoStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
