package com.mycompany.farmaciasystem.Presentacion.Login;

import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.farmaciasystem.Presentacion.Principal.Principal;
import com.mycompany.farmaciasystem.modelo.entidades.Usuario;
import com.mycompany.farmaciasystem.repository.Implementaciones.UsuarioRepositoryImpl;
import com.mycompany.farmaciasystem.repository.Interfaces.IUsuarioRepository;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        otrosComponentes();

    }

    private void otrosComponentes() {
        FlatLightLaf.setup();
        lblUsuario.requestFocus();
        txtUsuario.putClientProperty("JTextField.placeholderText", "Ingrese nombre de usuario");
        txtContrasenia.putClientProperty("JTextField.placeholderText", "*******");
        txtUsuario.putClientProperty("JTextField.showClearButton", true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIniciaSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVerContrasena = new javax.swing.JToggleButton();
        txtContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(238, 251, 253));
        txtUsuario.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 255)));
        txtUsuario.setPreferredSize(new java.awt.Dimension(15, 35));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 222, 306, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 184, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(29, 82, 109));
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 184, 209, 32));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 82, 109));
        jLabel6.setText("Contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, 209, 32));

        btnIniciaSesion.setBackground(new java.awt.Color(22, 120, 162));
        btnIniciaSesion.setFont(new java.awt.Font("Poppins SemiBold", 0, 21)); // NOI18N
        btnIniciaSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciaSesion.setText("Iniciar Sesión");
        btnIniciaSesion.setBorder(null);
        btnIniciaSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciaSesion.setFocusPainted(false);
        btnIniciaSesion.setFocusable(false);
        btnIniciaSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciaSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciaSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciaSesionMouseExited(evt);
            }
        });
        btnIniciaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 380, 199, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/logo2 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 361, -1));

        btnVerContrasena.setBackground(new java.awt.Color(238, 251, 253));
        btnVerContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/IconoirEye.png"))); // NOI18N
        btnVerContrasena.setBorder(null);
        btnVerContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 315, 40, 30));

        txtContrasenia.setBackground(new java.awt.Color(238, 251, 253));
        txtContrasenia.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasenia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 255)));
        txtContrasenia.setPreferredSize(new java.awt.Dimension(15, 35));
        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 313, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciaSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciaSesionMouseEntered

        btnIniciaSesion.setBackground(new Color(25, 99, 133));
    }//GEN-LAST:event_btnIniciaSesionMouseEntered

    private void btnIniciaSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciaSesionMouseExited
        btnIniciaSesion.setBackground(new Color(22, 120, 162));
    }//GEN-LAST:event_btnIniciaSesionMouseExited

    private void btnIniciaSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciaSesionMouseClicked

    }//GEN-LAST:event_btnIniciaSesionMouseClicked

    private void btnIniciaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaSesionActionPerformed

        String usuario = txtUsuario.getText().trim();
        char[] contraseniaChar = txtContrasenia.getPassword();
        String contrasenia = new String(contraseniaChar).trim();

        if (usuario.isEmpty() || contrasenia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos", " ❌ Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {

            IUsuarioRepository UserRepos = new UsuarioRepositoryImpl();
            Usuario Usuario = UserRepos.ValidarLogin(usuario, contrasenia);

            if (Usuario != null) {

                new Principal(Usuario).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Nombre de usuario o Contraseña incorrectos", " ❌ Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);

            }
        } catch (HeadlessException e) {
            System.out.println(e.toString());

        }


    }//GEN-LAST:event_btnIniciaSesionActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void btnVerContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerContrasenaActionPerformed

        if (txtContrasenia.getEchoChar() == 0) {
            txtContrasenia.setEchoChar('*');
        } else {
            txtContrasenia.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_btnVerContrasenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciaSesion;
    private javax.swing.JToggleButton btnVerContrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
